// Fichier généré par scripts/construire-sprite.mjs : ne pas modifier à la main.
export const NOMS_ICONES = [
  "hi-alert-circle",
  "hi-ambulatory-clinic",
  "hi-baby-0306m",
  "hi-blister-pills_oval_x4",
  "hi-blood-pressure",
  "hi-boy-0105y",
  "hi-chills-fever",
  "hi-community-healthworker",
  "hi-diabetes-measure",
  "hi-elderly",
  "hi-hospital",
  "hi-man",
  "hi-old-woman",
  "hi-pain",
  "hi-pharmacy",
  "hi-pregnant",
  "hi-stethoscope",
  "hi-syringe-vaccine",
  "hi-tooth",
  "hi-woman",
  "ph-arrow-left",
  "ph-backspace",
  "ph-bell",
  "ph-calendar-check",
  "ph-calendar-dots",
  "ph-caret-right",
  "ph-check-circle",
  "ph-cloud-arrow-up",
  "ph-house",
  "ph-list-checks",
  "ph-microphone",
  "ph-moon",
  "ph-pause",
  "ph-phone",
  "ph-pill",
  "ph-play",
  "ph-plus",
  "ph-sign-out",
  "ph-speaker-high",
  "ph-sun-horizon",
  "ph-sun",
  "ph-users-three",
  "ph-warning-circle",
  "ph-whatsapp-logo",
  "ph-wifi-slash",
  "ph-x",
] as const;

export type NomIcone = (typeof NOMS_ICONES)[number];
